name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci 

      # Step 4: Run Playwright tests and generate HTML report
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
              # Step 5: Verify report folder before upload
      - name: Check report folder
        if: always()
        run: |
          echo "Listing Playwright report folder contents..."
          ls -R playwright-report || echo "⚠️ playwright-report folder not found!"


      # Step 5: Upload the HTML report as artifact for Pages
      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report/

  # Step 6: Deploy report to GitHub Pages
  deploy:
    needs: test
    permissions:
      pages: write        # allow writing to GitHub Pages
      id-token: write     # required for deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
